source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def shared_pods
	pod 'Font-Awesome-Swift'
	pod 'R.swift'

	pod 'Alamofire', '~> 4.0'
	pod 'AlamofireImage'

	pod 'ObjectMapper', '~> 3.4'
	pod 'IQKeyboardManagerSwift'

	pod 'RealmSwift', '~> 4.3.1'
end

target 'movsea' do
    shared_pods
end

target 'movseaDebug' do
    shared_pods
end

